update to fix maxBrightness attribute not being set
fixes this error
java.lang.NullPointerException: Cannot invoke method toInteger() on null object on line 154 (setLevel)